'use strict';

module.exports = {
  CONSTRAINTS_VIOLATED: "CONSTRAINTS_VIOLATED",
  FAILED_ON_BLACKLISTED_EMAIL: "FAILED_ON_BLACKLISTED_EMAIL",
  RECIPIENT_IS_BLACKLISTED: "RECIPIENT_IS_BLACKLISTED",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  HTML_TEMPLATE_FILE_NOT_FOUND: "HTML_TEMPLATE_FILE_NOT_FOUND",
  OK: "OK"
}